spring:
  application:
    name: perfornalfinance
  datasource:
    url: jdbc:h2:mem:financedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
    fail-on-missing-locations: false
    baseline-on-migrate: true

server:
  port: 8888
  servlet:
    context-path: /api

